//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Brazilian_Portuguese {
            get {
                return ResourceManager.GetString("ModBot_Brazilian_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_English {
            get {
                return ResourceManager.GetString("ModBot_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_French {
            get {
                return ResourceManager.GetString("ModBot_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_German {
            get {
                return ResourceManager.GetString("ModBot_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:Italian MODS
        ///newversionmessage:Italian New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversiondismiss:Italian Dismiss
        ///newversioninstall:Italian Install
        ///modbotversion:Italian Mod-Bot Version: {0}
        ///modbotuptodate:Italian Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Italian Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Italian {
            get {
                return ResourceManager.GetString("ModBot_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Russian {
            get {
                return ResourceManager.GetString("ModBot_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Simplified_Chinese {
            get {
                return ResourceManager.GetString("ModBot_Simplified_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Spanish_LatinAmerica {
            get {
                return ResourceManager.GetString("ModBot_Spanish_LatinAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Spanish_Spain {
            get {
                return ResourceManager.GetString("ModBot_Spanish_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.2.
        /// </summary>
        internal static string ModBotVersion {
            get {
                return ResourceManager.GetString("ModBotVersion", resourceCulture);
            }
        }
    }
}
