//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODIFICAÇÕES
        ///newversion_message:Nova versão Mod-Bot disponível: {0}\n(versão atual: {1})
        ///newversion_dismiss:Dispensar
        ///newversion_install:Instalar
        ///modbotversion:Versão Mod-Bot: {0}
        ///modbotuptodate:Versão Mod-Bot &apos;{0}&apos; atualizada!
        ///ignoreallcrashes_savedwarning:Mensagem de opção salva (IgnoreCrashes): todas as falhas estão sendo ignoradas; isso só deve ser ativado para fins de teste; desative-o digitando &quot;ignoreallcrashes 0&quot; no console.
        ///ignoreallcrashes_on:O jogo agora está ignorando todas as  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Brazilian_Portuguese {
            get {
                return ResourceManager.GetString("ModBot_Brazilian_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:New Mod-Bot version available: {0}\n(Current version: {1})
        ///newversion_dismiss:Dismiss
        ///newversion_install:Install
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot version &apos;{0}&apos; up to date!
        ///ignoreallcrashes_savedwarning:Saved option message (IgnoreCrashes): All crashes are being ignored, this should only be enabled for testing purposes, turn it off by typing &quot;ignoreallcrashes 0&quot; into the console.
        ///ignoreallcrashes_on:The game is now ignoring all crashes, this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_English {
            get {
                return ResourceManager.GetString("ModBot_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:Nouvelle version Mod-Bot disponible: {0}\n(Version actuelle: {1})
        ///newversion_dismiss:Rejeter
        ///newversion_install:Installer
        ///modbotversion:Version Mod-Bot: {0}
        ///modbotuptodate:Version Mod-Bot &apos;{0}&apos; à jour!
        ///ignoreallcrashes_savedwarning:Message d&apos;option enregistré (IgnoreCrashes): Tous les plantages sont ignorés, cela ne doit être activé qu&apos;à des fins de test, désactivez-le en tapant &quot;ignoreallcrashes 0&quot; dans la console.
        ///ignoreallcrashes_on:Le jeu ignore désormais tous l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_French {
            get {
                return ResourceManager.GetString("ModBot_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:Modificationen.
        ///newversion_message:Eine neue Version von Mod-Bot ist verfügbar.: {0}\n(Aktuelle Version: {1})
        ///newversion_dismiss:Nicht machen.
        ///newversion_install:Instalieren.
        ///modbotversion:Mod-Bot Version: {0}
        ///modbotuptodate:Mod-Bot Version &apos;{0}&apos; ist auf dem neusten stand!
        ///ignoreallcrashes_savedwarning:Gespeicherte Nachricht (Ignoriere alle Abstürze): Alle Abstürze werden ignorierd, dies sollte nur für testenden Grund gemacht werden, schalte es aus indem du &quot;ignoreallcrashes 0&quot; in die Conso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_German {
            get {
                return ResourceManager.GetString("ModBot_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:Nuova versione Mod-Bot disponibile: {0}\n(Versione corrente: {1})
        ///newversion_dismiss:Respingere
        ///newversion_install:Installare
        ///modbotversion:Versione Mod-Bot: {0}
        ///modbotuptodate:Versione Mod-Bot &apos;{0}&apos; aggiornata!
        ///ignoreallcrashes_savedwarning:Messaggio di opzione salvato (IgnoreCrashes): tutti gli arresti anomali vengono ignorati, questo dovrebbe essere abilitato solo a scopo di test, disattivarlo digitando &quot;ignoreallcrashes 0&quot; nella console.
        ///ignoreallcrashes_on:Il g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Italian {
            get {
                return ResourceManager.GetString("ModBot_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODS
        ///newversion_message:利用可能な新しいMod-Botバージョン：{0}\n（現在のバージョン：{1}）
        ///newversion_dismiss:退出させる
        ///newversion_install:インストール
        ///modbotversion:Mod-Botバージョン：{0}
        ///modbotuptodate:Mod-Botバージョン &apos;{0}&apos;が最新です！
        ///ignoreallcrashes_savedwarning:保存されたオプションメッセージ（IgnoreCrashes）：すべてのクラッシュは無視されます。これはテスト目的でのみ有効にする必要があります。コンソールに「ignoreallcrashes 0」と入力してオフにしてください。
        ///ignoreallcrashes_on:ゲームは現在すべてのクラッシュを無視しています。このオプションはテスト用にのみ有効にする必要があります。 このオプションを有効にすると、ソフトクラッシュは無視されますが、ハードクラッシュが発生する可能性があります。
        ///ignoreallcrashes_off:ゲームはクラッシュを無視し [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Japanese {
            get {
                return ResourceManager.GetString("ModBot_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:개조
        ///newversion_message:새로운 Mod-Bot 버전 사용 가능 : {0}\n(현재 버전 : {1})
        ///newversion_dismiss:버리다
        ///newversion_install:설치
        ///modbotversion:Mod-Bot 버전 : {0}
        ///modbotuptodate:Mod-Bot 버전 &apos;{0}&apos;이 (가) 최신 상태입니다!
        ///ignoreallcrashes_savedwarning:저장된 옵션 메시지 (IgnoreCrashes) : 모든 충돌이 무시됩니다. 이것은 테스트 목적으로 만 활성화되어야합니다. 콘솔에 &quot;ignoreallcrashes 0&quot;을 입력하여 끄십시오.
        ///ignoreallcrashes_on:이제 게임이 모든 충돌을 무시하고 있습니다.이 옵션은 테스트 용으로 만 활성화해야합니다. 이 옵션을 활성화하면 소프트 크래시가 무시되지만 하드 크래시는 여전히 발생할 수 있습니다.
        ///ignoreallcrashes_off:게임이 더 이상 충돌을 무시하지 않습니다.이 옵션은 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Korean {
            get {
                return ResourceManager.GetString("ModBot_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:моды
        ///newversion_message:Доступна новая версия Mod-Bot: {0}\n(Текущая версия: {1})
        ///newversion_dismiss:Отклонить
        ///newversion_install:Установить
        ///modbotversion:Версия Mod-Bot: {0}
        ///modbotuptodate:Версия Mod-Bot &apos;{0}&apos; обновлена до последней версии!
        ///ignoreallcrashes_savedwarning:Сохраненная опция сообщения (IgnoreCrashes): все сбои игнорируются, это следует включить только для целей тестирования, отключите его, введя «ignoreallcrashes 0» в консоли.
        ///ignoreallcrashes_on:Игра теперь игнорирует все сб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Russian {
            get {
                return ResourceManager.GetString("ModBot_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:模组
        ///newversion_message:新的Mod-Bot版本可用: {0}\n(当前版本: {1})
        ///newversion_dismiss:解除
        ///newversion_install:安装
        ///modbotversion:Mod-Bot 版本: {0}
        ///modbotuptodate:Mod-Bot 版本 &apos;{0}&apos; 是最新的！
        ///ignoreallcrashes_savedwarning:保存的选项消息 (忽略崩溃): 所有崩溃均被忽略，仅应出于测试目的而启用，请在控制台中键入“ ignoreallcrashes 0”将其关闭。
        ///ignoreallcrashes_on:游戏现在将忽略所有崩溃，仅应启用此选项进行测试。 启用此选项将忽略软崩溃，但是崩溃仍然可能发生。
        ///ignoreallcrashes_off:游戏不再忽略崩溃，为游戏稳定起见，应始终关闭此选项。
        ///crashscreen_customtitle:Mod-Bot开发人员很乐意看到这一点！
        ///crashscreen_customdescription:将我们的屏幕截图发送给“机器人角斗场Mod-Bot”问题，以便 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Simplified_Chinese {
            get {
                return ResourceManager.GetString("ModBot_Simplified_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODIFICACIONES
        ///newversion_message:Nueva versión Mod-Bot disponible: {0}\n(Versión actual: {1})
        ///newversion_dismiss:Descartar
        ///newversion_install:Instalar en pc
        ///modbotversion:Versión Mod-Bot: {0}
        ///modbotuptodate:¡Versión de Mod-Bot &apos;{0}&apos; actualizada!
        ///ignoreallcrashes_savedwarning:Mensaje de opción guardada (IgnoreCrashes): se ignoran todos los bloqueos, esto solo debe habilitarse con fines de prueba, apáguelo escribiendo &quot;ignoreallcrashes 0&quot; en la consola.
        ///ignoreallcrashes_on:El juego ahora ig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Spanish_LatinAmerica {
            get {
                return ResourceManager.GetString("ModBot_Spanish_LatinAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modsbutton:MODIFICACIONES
        ///newversion_message:Nueva versión Mod-Bot disponible: {0}\n(Versión actual: {1})
        ///newversion_dismiss:Descartar
        ///newversion_install:Instalar en pc
        ///modbotversion:Versión Mod-Bot: {0}
        ///modbotuptodate:¡Versión de Mod-Bot &apos;{0}&apos; actualizada!
        ///ignoreallcrashes_savedwarning:Mensaje de opción guardada (IgnoreCrashes): se ignoran todos los bloqueos, esto solo debe habilitarse con fines de prueba, apáguelo escribiendo &quot;ignoreallcrashes 0&quot; en la consola.
        ///ignoreallcrashes_on:El juego ahora ig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModBot_Spanish_Spain {
            get {
                return ResourceManager.GetString("ModBot_Spanish_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.4.2.
        /// </summary>
        internal static string ModBotVersion {
            get {
                return ResourceManager.GetString("ModBotVersion", resourceCulture);
            }
        }
    }
}
